# Generated by Django 4.0.4 on 2022-05-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_created_by_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='http://localhost:8000/media/images/istockphoto-1257716991-612x612_SIa5LIi.jpg', upload_to='images/'),
        ),
    ]
